POST http://localhost:3001/convert
Content-Type: application/json

{
  "flowSid": "FWd09de1a720f5d681f518408a13aaf92d",
  "agentName": "Owlie",
  "businessName": "Owl Insurance"
}

###

POST https://se-hackathon-2025.fly.dev/convert
Content-Type: application/json

{
  "flowSid": "FWbf8b7cb08162c07fcf6c96fb3b8702f9",
  "agentName": "Owlie",
  "businessName": "Owl Insurance"
}

###





